title: KW UI/UX Design System
description: A guide for designers and developers at Kitware.
baseurl: /

include: ['_pages']

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.config.js
  - netlify.toml

collections:

  guidelines:
    archive_url: /guidelines/
    icon: ri-file-list-3-line
    output: true
    permalink: /:collection/:name
    title: Guidelines

  components:
    archive_url: /components/
    icon: ri-dashboard-line
    output: true
    permalink: /:collection/:name
    title: Components
