# config.yml

backend:
  name: git-gateway
  branch: integrate-netlify-cms # Branch to update (optional; defaults to master)

local_backend: true

media_folder: 'assets/uploads'

collections:
  - name: 'components'
    label: 'Components'
    folder: '_components/'
    fields:
      - { name: Title }
    files:
      - label: 'Alerts'
        name: 'alerts'
        file: 'alerts.html'
        fields:
          - { label: 'Title', name: 'title', widget: 'hidden', default: 'alerts' }
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'alerts' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'guidelines'
    label: 'Guidelines'
    folder: '_guidelines/'
    fields:
      - { name: Title }
